### PR TITLE
Create xjsx-router.js

### PR DESCRIPTION
**Pull request by Codinplus31**
I closed a pull request before because of a bug but i've fixed the bug
This is the syntax
```
<?xjsx-router: "/"?>
<div>Home page</div>
<div>Home pages</div>

<?end?>
<?xjsx-router: "/#about"?>
<div>About page</div>
<?end?>
<!--- to check if page doesn't exist you use this -->
<!-- or -->
<?xjsx-router: ""?>
<div> page not found</div>
<div> page not </div>

<?end?>
<a href="#about">router</a>
<a href="#abot">routr</a>

```

### CODE REVIEW

**Comment by Codinplus31** [comment]
You can also use this to check if page is not found
<?xjsx-router: "*"?>
<div> page not found</div>
<div> page not </div>

<?end?>

**Comment by Codinplus31** [comment]
You can also use this to check if page is not found
`<?xjsx-router: "*"?>
<div> page not found</div>
<div> page not </div>

<?end?>`

**Comment by Codinplus31** [comment]
You can also use this to check if page is not found
```
<?xjsx-router: "*"?>
<div> page not found</div>
<div> page not </div>

<?end?>
```

**Comment by OwensAkpede** [comment]
sorry for late reply broo... hv'been busy

**Pull request merged**
